version: "3.9"
services:
  web:
    build: .
    env_file:
    - .env.production
    ports:
      - "3000:3000"

  backend:
    build: .
    env_file:
    - .env.production
    ports:
      - "3000:3000"